%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.15.2

-ifndef(all_pb).
-define(all_pb, true).

-define(all_pb_gpb_version, "4.15.2").

-ifndef('M_1001_TOS_PB_H').
-define('M_1001_TOS_PB_H', true).
-record(m_1001_tos,
        {id = []                :: iodata() | undefined % = 1, optional
        }).
-endif.

-ifndef('M_1001_TOC_PB_H').
-define('M_1001_TOC_PB_H', true).
-record(m_1001_toc,
        {
        }).
-endif.

-ifndef('M_2001_TOS_PB_H').
-define('M_2001_TOS_PB_H', true).
-record(m_2001_tos,
        {t = 0                  :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-ifndef('M_2001_TOC_PB_H').
-define('M_2001_TOC_PB_H', true).
-record(m_2001_toc,
        {t = 0                  :: non_neg_integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-endif.
